# Generated by Django 5.2.3 on 2025-06-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок объявления')),
                ('property_type', models.CharField(choices=[('new', 'Новостройка'), ('resale', 'Вторичное жилье')], default='resale', max_length=10, verbose_name='Тип недвижимости')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес/Район')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (м²)')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Количество комнат')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('main_photo', models.ImageField(upload_to='property_photos/', verbose_name='Главное фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное объявление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/', verbose_name='Фотография')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt текст')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Фотография объекта',
                'verbose_name_plural': 'Фотографии объектов',
            },
        ),
    ]
