# Generated by Django 5.2.3 on 2025-06-13 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-date_added'], 'verbose_name': 'Объект недвижимости', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False, verbose_name='Балкон / Лоджия'),
        ),
        migrations.AddField(
            model_name='property',
            name='bus_stop_nearby',
            field=models.BooleanField(default=False, verbose_name='Остановка транспорта рядом'),
        ),
        migrations.AddField(
            model_name='property',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок сдачи'),
        ),
        migrations.AddField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='property',
            name='developer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Лифт'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Меблирована'),
        ),
        migrations.AddField(
            model_name='property',
            name='gas_supply',
            field=models.BooleanField(default=False, verbose_name='Газоснабжение'),
        ),
        migrations.AddField(
            model_name='property',
            name='gym',
            field=models.BooleanField(default=False, verbose_name='Тренажерный зал'),
        ),
        migrations.AddField(
            model_name='property',
            name='heating_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип отопления'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='property',
            name='kindergarten_nearby',
            field=models.BooleanField(default=False, verbose_name='Детский сад рядом'),
        ),
        migrations.AddField(
            model_name='property',
            name='maternity_capital',
            field=models.BooleanField(default=False, verbose_name='Материнский капитал'),
        ),
        migrations.AddField(
            model_name='property',
            name='metro_nearby',
            field=models.BooleanField(default=False, verbose_name='Метро рядом'),
        ),
        migrations.AddField(
            model_name='property',
            name='military_mortgage',
            field=models.BooleanField(default=False, verbose_name='Военная ипотека'),
        ),
        migrations.AddField(
            model_name='property',
            name='mortgage_possible',
            field=models.BooleanField(default=False, verbose_name='Возможна ипотека'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='property',
            name='playground',
            field=models.BooleanField(default=False, verbose_name='Детская площадка'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена за м²'),
        ),
        migrations.AddField(
            model_name='property',
            name='renovation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ремонт (например: дизайнерский, косметический)'),
        ),
        migrations.AddField(
            model_name='property',
            name='school_nearby',
            field=models.BooleanField(default=False, verbose_name='Школа рядом'),
        ),
        migrations.AddField(
            model_name='property',
            name='security',
            field=models.BooleanField(default=False, verbose_name='Охрана'),
        ),
        migrations.AddField(
            model_name='property',
            name='sewage_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип канализации'),
        ),
        migrations.AddField(
            model_name='property',
            name='swimming_pool',
            field=models.BooleanField(default=False, verbose_name='Бассейн'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этажность дома'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_supply_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип водоснабжения'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание объекта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('new_development', 'Новостройка'), ('resale', 'Вторичное жилье')], max_length=20, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_photos/gallery/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Объект недвижимости'),
        ),
    ]
